# Generated by Django 6.1.1 on 2026-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
